version: "3"

services:
  storybook:
    container_name: masks-storybook
    build:
      context: ./masks-front/
      dockerfile: ./.storybook/Dockerfile
    environment:
      - NODE_ENV
    ports:
      - 6006:6006
    volumes:
      - ./masks-front/src:/app/src
      - ./masks-front/public:/app/public
      - ./masks-front/.env:/app/.env
      - ./masks-front/tsconfig.json:/app/tsconfig.json
      - ./masks-front/package.json:/app/package.json
      - ./masks-front/.storybook:/app/.storybook
      - mongodata:/data/db
    command: ["yarn", "storybook"]
  back:
    container_name: masks-back
    build:
      context: ./masks-back/
      dockerfile: ./Dockerfile
    environment:
      - NODE_ENV
      - PORT
    ports:
      - 4000:4000
    volumes:
      - ./masks-back/src:/app/src
      - ./masks-back/.env:/app/.env
      - ./masks-back/tsconfig.json:/app/tsconfig.json
      - ./masks-back/package.json:/app/package.json
      - mongodata:/data/db
    command: ["npm", "run", "start:prod"]
  market:
    container_name: masks-market
    build:
      context: ./masks-market/
      dockerfile: ./Dockerfile
    environment:
      - NODE_ENV
      - API_URL
    ports:
      - 3010:3010
    volumes:
      - ./masks-market/src:/app/src
      - ./masks-market/public:/app/public
      - ./masks-market/.env:/app/.env
      - ./masks-market/tsconfig.json:/app/tsconfig.json
      - ./masks-market/package.json:/app/package.json
      - mongodata:/data/db
    command: ["./node_modules/.bin/next", "start", "-p", "3010"]
volumes:
  mongodata:
