version: "3"

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./dockerfiles/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      - 8080:8080
      - 443:443
  mongo:
    build: ./dockerfiles/mongo/
    volumes:
      - mongodata:/data/db
      - ./dockerfiles/mongo/mongod.conf:/etc/mongo/mongod.conf
    ports:
      - 27017:27017
volumes:
  mongodata:
