version: "3"

services:
  vault:
    container_name: vault
    image: vault:latest
    volumes:
      - ./vault/config:/vault/config
      - ./vault/policies:/vault/policies
      - ./vault/data:/vault/data
    ports:
      - 4010:4010
    environment:
      - VAULT_ADDR=http://0.0.0.0:4010
      - VAULT_API_ADDR=http://0.0.0.0:4010
      - VAULT_ADDRESS=http://0.0.0.0:4010
      - VAULT_DEV_LISTEN_ADDRESS=http://0.0.0.0:4010
      - VAULT_DEV_ROOT_TOKEN_ID=myroot
    cap_add:
      - IPC_LOCK
    command: vault server -config=/vault/config/vault.hcl
  nginx:
    container_name: nginx
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      - 8080:8080
      - 443:443
    depends_on:
      - mongo
      - vault
      - back
      - landing
      - market
  mongo:
    container_name: mongo
    build: ./mongo/
    volumes:
      - mongodata:/data/db
      - ./mongo/mongod.conf:/etc/mongo/mongod.conf
    ports:
      - 27017:27017
  back:
    container_name: back
    build:
      context: ./masks.be/
      dockerfile: ../masks.be/Dockerfile
    env_file:
      - ./masks.be/.env
    ports:
      - 4000:4000
    volumes:
      - ./masks.be:/back
      - mongodata:/data/db
    depends_on:
      - mongo
      - vault
    command: ["yarn", "start:dev"]
  landing:
    container_name: landing
    build:
      context: ../masks.fe.landing/
      dockerfile: ../masks.fe.landing/Dockerfile
    env_file:
      - ../masks.fe.landing/.env
    ports:
      - 3000:3000
    volumes:
      - ../masks.fe.landing:/landing
    depends_on:
      - mongo
      - back
    command: ["yarn", "dev", "-p", "3000"]
  market:
    container_name: market
    build:
      context: ../masks.fe.market/
      dockerfile: ../masks.fe.market/Dockerfile
    env_file:
      - ../masks.fe.market/.env
    ports:
      - 3010:3010
    volumes:
      - ../masks.fe.market:/market
    depends_on:
      - mongo
      - back
    command: ["yarn", "dev", "-p", "3010"]
  storybook:
    container_name: storybook
    build:
      context: ../masks.fe.landing/
      dockerfile: ../dockerfiles/masks.fe.landing/.storybook/Dockerfile
    env_file:
      - ../masks.fe.landing/.env
    ports:
      - 6006:6006
    volumes:
      - ../masks.fe.landing:/storybook
    command: ["yarn", "storybook"]
volumes:
  mongodata:
